name: GCP Build and Deploy to Cloud Run

on:
  push:
    branches:
      - test-gcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker web-app
        id: docker_build
        run: |
          docker build -t web-app ./web-app
          echo "::set-output name=build_status::success"
      
      - name: Check Build Status
        run: |
          if [ "${{ steps.docker_build.outputs.build_status }}" == "success" ]; then
            echo "Docker build successful"
          else
            echo "Docker build failed"
            exit 1
          fi

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          #export_default_credentials: true

      - name: Build and push Docker image to GCR
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/web-app:${{ github.sha }} ./web-app
          echo "Built image: gcr.io/${{ secrets.PROJECT_ID }}/web-app:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-cloud-run-service \
            --image gcr.io/${{ secrets.PROJECT_ID }}/web-app:${{ github.sha }} \
            --platform managed \
            --region us-central1
