name: GCP Build and Deploy to Cloud Run

on:
  push:
    branches:
      - test-gcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with GCP
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Build and push the Docker image to GCR
      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/web-app:${{ github.sha }}
        env:
          IMAGE_NAME: web-app

      # Deploy the container to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy <SERVICE_NAME> \
            --image gcr.io/<YOUR_PROJECT_ID>/web-app:${{ github.sha }} \
            --platform managed \
            --region us-central1
        env:
          SERVICE_NAME: your-cloud-run-service

